package com.horizen.csw

import com.horizen.cryptolibprovider.implementations.CswCircuitImplZendoo
import com.horizen.secret.{PrivateKey25519, PrivateKey25519Creator}
import com.horizen.utils.BytesUtils
import org.bouncycastle.math.ec.rfc8032.Ed25519
import org.junit.Assert.assertEquals
import org.junit.Test

import java.lang.reflect.Method

class CswCircuitUtilsTest {
  val cswCircuit = new CswCircuitImplZendoo()

  @Test
  def transformPrivateKey25519(): Unit = {
    val pk: PrivateKey25519 = PrivateKey25519Creator.getInstance().generateSecret("seed".getBytes)

    val scalar = cswCircuit.privateKey25519ToScalar(pk)

    // Using reflection execute Bouncy castle method to generate Public key from the scalar
    // and verify that resulting PubKey is the same.
    val pubKey = new Array[Byte](32)
    val m: Method = classOf[Ed25519].getDeclaredMethod("scalarMultBaseEncoded", classOf[Array[Byte]], classOf[Array[Byte]], classOf[Int])
    m.setAccessible(true)
    m.invoke(classOf[Ed25519], scalar, pubKey, Integer.valueOf(0))

    assertEquals("Different public key than the one generated by BouncyCastle.",
      BytesUtils.toHexString(pk.publicImage().pubKeyBytes()), BytesUtils.toHexString(pubKey))

    // Regression
    assertEquals("Different pub key", "415bf2bf63fc5b566a94e6f2d18e15c6d2b819bad38f93b1fb277b34fbe68504", BytesUtils.toHexString(pk.publicImage().pubKeyBytes()))
    assertEquals("Different private key", "e5a75e0836c59813dd775e888b9c5fda325565b4ca159d1bc8c81923e5ffffff", BytesUtils.toHexString(pk.privateKey()))
    assertEquals("Different transformation result", "80fb501f4849d8b83c035930cce66c9ba1c79c2e7c9004ba22015baa16da7656", BytesUtils.toHexString(scalar))
  }
}
